### PR TITLE
refactor(synonyms): rename replaceExistingSynonyms

### LINKED ISSUE #438: Rename `replaceExistingSynonyms` to `clearExistingSynonyms`
The parameter `replaceExistingSynonyms` in the `saveSynonyms` method is inconsistent with the rest of our API. We should rename it to `clearExistingSynonyms`. Backward-compatibility should be kept in mind

### PR DESCRIPTION
**Pull request by chloelbn**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | no     
| Related Issue     | Fix #438 
| Need Doc update   | yes

## Describe your change

In the method `saveSynonyms`, rename the parameter `replaceExistingSynonyms` to `clearExistingSynonyms`

### CODE REVIEW

**Review by DevinCodes — DISMISSED** [review]

**Comment by DevinCodes** [comment]
Should we add a test with the new parameter?

**Review by DevinCodes — COMMENTED** [review]
Same comment as in the PR for the PHP client: I think we should add tests to 100% ensure backwards compatibility. WDYT?

**Comment by chloelbn** [comment]
@DevinCodes done!

**Review by DevinCodes — APPROVED** [review]

**Comment by chloelbn** [comment]
closing this for the moment, will reopen if the changes were to happen

**Pull request closed without merging**
