### PR TITLE
Remove Gemfile.lock

### PR DESCRIPTION
**Pull request by timcraft**
The Gemfile.lock file should not be checked into version control:

http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

### CODE REVIEW

**Comment by raphi** [comment]
@timcraft can you update the Gemfile as well? Thx

**Comment by timcraft** [comment]
@raphi Not sure what you mean, what needs updating in the Gemfile and how is that related to this pull request? The Gemfile.lock file doesn't need to be included in a gem.

**Comment by raphi** [comment]
@timcraft sorry if it wasn't clear: I was referring to the part of adding `gemspec` in the Gemfile while removing dependencies duplicates.

**Comment by Jerskouille** [comment]
Done in #257 . :)

**Pull request closed without merging**
