### PR TITLE
Make HttpClient transparent_gzip_decompression configurable

### PR DESCRIPTION
**Pull request by pimpin**
Transparent gzip decompression in not compatible with httplog gem.

Fix https://github.com/algolia/algoliasearch-rails/issues/273

### CODE REVIEW

**Comment by pimpin** [comment]
You might be right, I did not check in the HttpClient source yet.
But it is only for dev purpose.
Could we add it to configuration set ? Do you have other suggestion to make it compatible with httplog ?

**Comment by Jerskouille** [comment]
I believe that if you were to expose a client configuration option as for `@ssl = data[:ssl].nil? ? true : data[:ssl]`, this should be considerable cc @redox ?

**Comment by redox** [comment]
> I believe that if you were to expose a client configuration option as for @ssl = data[:ssl].nil? ? true : data[:ssl], this should be considerable cc @redox ?

Yes, this could be an option. We could have a `:gzip` option.

**Comment by pimpin** [comment]
Thanks for suggestion @Jerskouille . @redox Could you implement it please ?
I'll be happy to test the branch as soon as possible and give you any feedback nedded.

**Comment by Jerskouille** [comment]
Actually @pimpin , since this is your PR, I believe you should be able to modify your code without too much hassle. :)

**Comment by pimpin** [comment]
@Jerskouille I first did not see the link with `@ssl = data[:ssl].nil? ? true : data[:ssl]` . But I think I get it.

I did not try this yet. I will tonight.
@redox could you confirm if this is seems ok for you please ?

If my issue is fixed, I might also try to add a spec and squash this.

**Comment by pimpin** [comment]
I've tried it and it works for us.
I've rebased and skip the spec part :innocent: 
Is this ok for you ? @redox

**Comment by Jerskouille** [comment]
Can you maybe call it only `@gzip`? Otherwise, I believe we're good to go, and I'd be happy to merge it.

**Comment by pimpin** [comment]
I'm not really aware of the reason why this param is called `transprent_gzip_compression` in HttpClient ; But I do believe in sharpness over shortness importance when dealing with naming.
But it's your choice and it's ok for me.

**Comment by Jerskouille** [comment]
To answer your comment, I agree with you.
However in this case, setting this to false effectively disables `gzip` entirely for the client, hence making a good case, at least for me, for a short yet clear option.

**Pull request merged**
